apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: schedule-rs
build:
  artifacts:
    - image: schedule-rs
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
